package org.sharkk2.shrkengine.engine.classes;

import org.joml.Matrix4f;
import org.joml.Vector3f;
import org.sharkk2.shrkengine.engine.Camera;
import org.sharkk2.shrkengine.engine.Engine;
import org.sharkk2.shrkengine.engine.LightManager;
import org.sharkk2.shrkengine.engine.helpers.Utils;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.lwjgl.glfw.GLFW.glfwGetTime;

public abstract class Scene {
    protected String sceneName;
    protected final Engine engine;
    protected final Camera camera;
    protected final List<Entity2D> screenEntities = new ArrayList<>();
    protected final List<Entity3D> worldEntities = new ArrayList<>();
    protected final Map<String, Entity3D> worldEntityMap = new HashMap<>();
    protected final Map<String, Entity3D> worldPosMap = new HashMap<>();
    protected final Map<String, Entity2D> screenEntityMap = new HashMap<>();

    public final GlobalSceneLight globalSceneLight = new GlobalSceneLight();
    public final Time sceneTime = new Time(this);
    public final Fog sceneFog = new Fog();


    public static class GlobalSceneLight {
        public Vector3f direction = new Vector3f(0.3f, -1.0f, 0.5f).normalize();
        public Vector3f color = new Vector3f(1.0f, 0.95f, 0.85f);
        public Vector3f ambient = new Vector3f(0.2f, 0.2f, 0.2f);
        public LightManager.ShadowMap shadowMap = new LightManager.ShadowMap();
        public boolean castShadow = true;
        public boolean enabled = true;

        public void setAmbient(float r, float g, float b) {ambient.set(r,g,b);}
        public void setDirection(Vector3f direction) {
            this.direction = direction.normalize();
            float sunHeight = direction.negate(new Vector3f()).y;
            float dayBlend = Math.max(sunHeight * 2.0f, 0.0f);

            float ambientStrength = 0.01f + 0.19f * dayBlend;
            setAmbient(ambientStrength, ambientStrength, ambientStrength);
        }
        public void setColor(float r, float g, float b) {color.set(r,g,b);}
        public void setShadow(boolean v) {castShadow = v;}
        public void enable(boolean v) {enabled = v;}

        public Matrix4f getLightSpace(Camera camera) {
            float size = 32;
            Matrix4f lightSpace = new Matrix4f();
            Matrix4f lightProj = new Matrix4f().ortho(-size, size, -size, size, 1f, 300f);
            Vector3f lightDir = new Vector3f(direction).normalize();
            Vector3f target = new Vector3f(camera.getPosition());
            float texelSize = (size * 2f) / LightManager.ShadowMap.SHADOW_WIDTH;
            target.x = (float)(Math.floor(target.x / texelSize) * texelSize);
            target.z = (float)(Math.floor(target.z / texelSize) * texelSize);

            Vector3f lightPos = new Vector3f(target).sub(new Vector3f(lightDir).mul(80f));
            Matrix4f lightView = new Matrix4f().lookAt(lightPos, target, new Vector3f(0f, 1f, 0f));

            lightProj.mul(lightView, lightSpace);
            return lightSpace;
        }
    }

    public static class Time {
        public double dayLength = 180;
        private Scene scene;
        private double time;

        public Time(Scene scene) {
            this.scene = scene;

        }

        public double getDayLength() {return dayLength;}
        public void setDayLength(double dayLength) {this.dayLength = dayLength;}
        public double getTime() {return time;}
        public void setTime(double t) {
            this.time = t;
            double angle = time * 2 * Math.PI;
            Vector3f lightDir = new Vector3f(0, (float)Math.sin(angle), (float)Math.cos(angle)).normalize();
            scene.globalSceneLight.setDirection(lightDir);
            scene.sceneFog.setColor(getSkyColor(true));
        }

        public void tick() {
            double t = glfwGetTime();
            time = (t % dayLength) / dayLength;
            double angle = time * 2 * Math.PI;
            Vector3f lightDir = new Vector3f(0, (float)Math.sin(angle), (float)Math.cos(angle)).normalize();
            scene.globalSceneLight.setDirection(lightDir);
            scene.sceneFog.setColor(getSkyColor(true));
        }

        public Vector3f getSkyColor(boolean dayNightCycle) { // function generated by claude
            // this should mirror the same math in the skybox shader
            Vector3f sDir = scene.globalSceneLight.direction.negate(new Vector3f());
            float sunHeight = sDir.y;
            Vector3f zenithColor, midColor, horizonColor, hazeColor;
            if (dayNightCycle) {
                float dayBlend = Math.min(Math.max(sunHeight * 2.0f, 0.0f), 1.0f);
                float sunsetBlend = Math.min(Math.max(1.0f - Math.abs(sunHeight) * 3.0f, 0.0f), 1.0f);

                Vector3f dayZenith = new Vector3f(0.08f, 0.15f, 0.45f);
                Vector3f dayMid = new Vector3f(0.25f, 0.52f, 0.85f);
                Vector3f dayHorizon = new Vector3f(0.72f, 0.84f, 0.98f);
                Vector3f dayHaze = new Vector3f(0.9f,0.75f, 0.6f);
                Vector3f sunsetZenith = new Vector3f(0.05f, 0.05f, 0.25f);
                Vector3f sunsetMid = new Vector3f(0.6f,  0.25f, 0.1f);
                Vector3f sunsetHorizon = new Vector3f(1.0f,  0.45f, 0.1f);
                Vector3f sunsetHaze = new Vector3f(1.0f,  0.4f,  0.15f);
                Vector3f nightZenith = new Vector3f(0.01f, 0.01f, 0.05f);
                Vector3f nightMid = new Vector3f(0.02f, 0.02f, 0.08f);
                Vector3f nightHorizon = new Vector3f(0.04f, 0.04f, 0.12f);
                Vector3f nightHaze = new Vector3f(0.03f, 0.03f, 0.1f);

                zenithColor = Utils.mix(Utils.mix(nightZenith, sunsetZenith, dayBlend), dayZenith, dayBlend);
                midColor = Utils.mix(Utils.mix(nightMid,sunsetMid, dayBlend), dayMid, dayBlend);
                horizonColor = Utils.mix(Utils.mix(nightHorizon, sunsetHorizon, dayBlend), dayHorizon, dayBlend);
                hazeColor = Utils.mix(Utils.mix(nightHaze, sunsetHaze, dayBlend), dayHaze, dayBlend);

                zenithColor = Utils.mix(zenithColor, sunsetZenith,sunsetBlend * 0.5f);
                horizonColor = Utils.mix(horizonColor, sunsetHorizon, sunsetBlend * 0.8f);
                hazeColor = Utils.mix(hazeColor, sunsetHaze,sunsetBlend * 0.9f);
            } else {
                zenithColor = new Vector3f(0.08f, 0.15f, 0.45f);
                midColor = new Vector3f(0.25f, 0.52f, 0.85f);
                horizonColor = new Vector3f(0.72f, 0.84f, 0.98f);
                hazeColor = new Vector3f(0.9f,  0.75f, 0.6f);
            }

            float t = 0f; // change this to sample at a different sky height

            Vector3f skyColor = Utils.mix(horizonColor, midColor, Utils.smoothstep(0.0f, 0.25f, t));
            skyColor = Utils.mix(skyColor, zenithColor, Utils.smoothstep(0.15f, 1.0f, t));

            float hazeBand = (float)(Math.exp(-t * 20.0) * Math.min(Math.max(1.0f - Math.abs(t) * 6.0f, 0.0f), 1.0f));
            skyColor = Utils.mix(skyColor, hazeColor, hazeBand * 0.5f);
            return skyColor;
        }
    }

    public static class Fog {
        public Vector3f color = new Vector3f(0.5f, 0.6f, 0.7f);
        public float start = 20f;
        public float end = 80f;
        public float density = 0.05f;
        public final int EXPONENTIAL = 1;
        public final int LINEAR = 0;
        public final int DISABLED = -1;
        public int mode = 1;

        public void setMode(int mode) {this.mode = mode;}
        public void setColor(Vector3f color) {this.color.set(color);}
        public void setColor(float r, float g, float b) {color.set(r,g,b);}
        public void setRange(float start, float end) {this.start = start; this.end = end;}
        public void setDensity(float d) {density=d;}
    }

    protected Scene(Engine engine, String sceneName) {
      this.engine = engine;
      this.sceneName = sceneName;
      camera = engine.getCamera();
    }

    public abstract void load();
    public abstract void tick();
    public abstract void onDestroy();
    public abstract void onScreenResize(int oldWidth, int oldHeight);

    public Map<String, Entity3D> getWorldMap() {return worldEntityMap;}
    public List<Entity2D> getScreenEntities() {return screenEntities;}
    public List<Entity3D> getWorldEntities() {return worldEntities;}
    public void addWorldEntity(Entity3D e) {
        worldEntities.add(e); worldEntityMap.put(e.getID(), e); worldPosMap.put(e.x + ":" + e.y + ":" + e.z, e);
    }

    public void addScreenEntity(Entity2D e) {screenEntities.add(e); screenEntityMap.put(e.getID(), e);}
    public Entity3D getWorldEntity(String id) {return worldEntityMap.get(id);}
    public Entity2D getScreenEntity(String id) {return screenEntityMap.get(id);}
    public Entity3D getEntityAt(float x, float y, float z, boolean rounded) {
        if (rounded) {
            x = (float)Math.floor(x);
            y = (float)Math.floor(y);
            z = (float)Math.floor(z);
        }
        return worldPosMap.get(x + ":" + y + ":" + z);
    }

    public String getName() {return sceneName;}
    public void destroy() {
        onDestroy();
        for (Entity3D e : worldEntities) {
            e.cleanup();
        }
        worldEntities.clear();
        worldEntityMap.clear();
        screenEntityMap.clear();
        screenEntities.clear();
    }
}
